export const DEFAULT_USER_PROFILE = {
  userId: 'usr_local_8742',
  name: 'Jane Doe (You)',
  joinedDate: '2026-06-17T00:00:00Z',
  points: 320,
  level: 2,
  co2Target: 14.5,
  currentCo2: 12.8,
  ecoScore: 82,
  stats: {
    transport: 4.8,
    food: 3.6,
    energy: 3.2,
    lifestyle: 1.2,
  },
};

export const DEFAULT_ACTIVITY_LOGS = [
  {
    id: 'log_987654',
    timestamp: '2026-06-17T19:56:00Z',
    category: 'transport',
    activity: 'Rode electric bike instead of driving',
    value: 10.0,
    unit: 'km',
    co2Avoided: 2.1,
    co2Produced: 0.0,
    pointsEarned: 25,
  },
  {
    id: 'log_987653',
    timestamp: '2026-06-17T14:30:00Z',
    category: 'food',
    activity: 'Ate vegetarian lunch instead of beef',
    value: 1.0,
    unit: 'meal',
    co2Avoided: 1.5,
    co2Produced: 0.4,
    pointsEarned: 20,
  },
];

export const DEFAULT_CHALLENGES = [
  {
    id: 'ch_554433',
    title: 'Meatless Weekdays',
    description: 'Eat vegetarian or vegan meals from Monday to Friday.',
    category: 'food',
    difficulty: 'medium',
    durationDays: 5,
    pointsReward: 150,
    co2SavingsEst: 12.5,
    progress: 60,
    status: 'active',
  },
  {
    id: 'ch_554434',
    title: 'Pedal Power Week',
    description: 'Commute via bike or walk for all trips under 5km.',
    category: 'transport',
    difficulty: 'hard',
    durationDays: 7,
    pointsReward: 250,
    co2SavingsEst: 18.0,
    progress: 20,
    status: 'available',
  },
  {
    id: 'ch_554435',
    title: 'Zero Standby Power',
    description: 'Turn off all electronics at the power strip before bed.',
    category: 'energy',
    difficulty: 'easy',
    durationDays: 3,
    pointsReward: 60,
    co2SavingsEst: 4.5,
    progress: 0,
    status: 'available',
  },
];

export const DEFAULT_LEADERBOARD = [
  { rank: 1, name: 'Alex Green', avatar: '🌿', ecoScore: 96, co2AvoidedTotal: 84.5 },
  { rank: 2, name: 'Sarah Solar', avatar: '☀️', ecoScore: 91, co2AvoidedTotal: 65.2 },
  { rank: 3, name: 'Jane Doe (You)', avatar: '🌎', ecoScore: 82, co2AvoidedTotal: 12.8 },
  { rank: 4, name: 'David Wind', avatar: '💨', ecoScore: 76, co2AvoidedTotal: 34.1 },
  { rank: 5, name: 'Emma Earth', avatar: '🌱', ecoScore: 68, co2AvoidedTotal: 18.9 },
];

export const PRESETS = {
  transport: [
    {
      title: 'Rode electric bike instead of driving',
      val: 10,
      unit: 'km',
      co2Avoided: 2.1,
      co2Produced: 0.0,
      points: 25,
    },
    {
      title: 'Took electric train (commute)',
      val: 25,
      unit: 'km',
      co2Avoided: 4.2,
      co2Produced: 0.3,
      points: 35,
    },
    {
      title: 'Carpooled with coworkers',
      val: 15,
      unit: 'km',
      co2Avoided: 1.8,
      co2Produced: 1.2,
      points: 15,
    },
  ],
  food: [
    {
      title: 'Ate vegetarian or vegan meal',
      val: 1,
      unit: 'meal',
      co2Avoided: 1.5,
      co2Produced: 0.4,
      points: 20,
    },
    {
      title: 'Purchased local organic produce',
      val: 1,
      unit: 'count',
      co2Avoided: 0.8,
      co2Produced: 0.1,
      points: 15,
    },
    {
      title: 'Composted organic food waste',
      val: 1,
      unit: 'count',
      co2Avoided: 0.5,
      co2Produced: 0.0,
      points: 10,
    },
  ],
  energy: [
    {
      title: 'Transition to LED bulbs (Replace 5)',
      val: 5,
      unit: 'count',
      co2Avoided: 0.75,
      co2Produced: 0.0,
      points: 40,
    },
    {
      title: 'Set thermostat to 24°C in summer',
      val: 8,
      unit: 'hours',
      co2Avoided: 1.2,
      co2Produced: 0.0,
      points: 30,
    },
    {
      title: 'Air-dried clothes instead of dryer',
      val: 1,
      unit: 'load',
      co2Avoided: 1.8,
      co2Produced: 0.0,
      points: 25,
    },
  ],
  lifestyle: [
    {
      title: 'Brought reusable bags & bottles',
      val: 1,
      unit: 'count',
      co2Avoided: 0.3,
      co2Produced: 0.0,
      points: 10,
    },
    {
      title: 'Recycled plastics, paper & tin',
      val: 1,
      unit: 'count',
      co2Avoided: 0.4,
      co2Produced: 0.0,
      points: 10,
    },
    {
      title: 'Purchased second-hand clothing',
      val: 1,
      item: 'item',
      co2Avoided: 4.5,
      co2Produced: 0.0,
      points: 50,
    },
  ],
};

export const COACH_RECS = [
  {
    category: 'energy',
    title: 'Transition to LED bulbs',
    description: 'Replace 5 halogen bulbs in your living room. Saves approx. 0.75kg CO2 per day.',
    co2Savings: 0.75,
    difficulty: 'easy',
    pointsReward: 40,
  },
  {
    category: 'food',
    title: 'Adopt Meatless Monday',
    description: 'Enjoy entirely plant-based meals for one full day. Saves approx. 4.5kg CO2.',
    co2Savings: 4.5,
    difficulty: 'easy',
    pointsReward: 50,
  },
  {
    category: 'transport',
    title: 'Commute via Electric Bike',
    description: 'Cycle a 10km commute instead of driving a petrol car. Saves approx. 2.1kg CO2.',
    co2Savings: 2.1,
    difficulty: 'medium',
    pointsReward: 30,
  },
  {
    category: 'lifestyle',
    title: 'Ditch Single-Use Water Bottles',
    description: 'Use a steel bottle for 2 weeks. Saves approx. 1.2kg CO2 and prevents waste.',
    co2Savings: 1.2,
    difficulty: 'easy',
    pointsReward: 25,
  },
  {
    category: 'energy',
    title: 'Unplug Idle Devices',
    description: 'Unplug your home office setup before bed. Saves approx. 0.3kg CO2 per night.',
    co2Savings: 0.3,
    difficulty: 'easy',
    pointsReward: 15,
  },
];
